"""make_slides.py — 生成 Candice prompt + demo + evaluation framework 的 deck。

三部分:
  1. 改版后的 prompt(结构 + 关键段落)
  2. 用这个 prompt 真跑出来的输出(tools/probe_prompt.py 与 probe_multiturn.py 的结果)
  3. 评估框架(四大类 + 四张关系图)

demo 里的患者回复全部来自实跑,不是手写示例。多轮那一页故意展示的是
一个**未通过**的结果 —— 它正好是 within-session state dynamics 那条指标要抓的东西。

用法: python3 tools/make_slides.py [图片目录]
"""
import sys
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

ROOT = Path(__file__).resolve().parent.parent
IMG = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'figures'
OUT = ROOT / 'Candice_Prompt_Demo_Evaluation.pptx'

W, H = Inches(13.333), Inches(7.5)
INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTE = RGBColor(0x6B, 0x72, 0x78)
FAINT = RGBColor(0x9A, 0xA0, 0xA6)
BLUE = RGBColor(0x1E, 0x6F, 0xD9)
RED = RGBColor(0xB0, 0x2A, 0x26)
GREEN = RGBColor(0x1A, 0x8F, 0x4C)
ORANGE = RGBColor(0xE0, 0x7B, 0x00)
BG_SOFT = RGBColor(0xF7, 0xF8, 0xF9)

prs = Presentation()
prs.slide_width, prs.slide_height = W, H
BLANK = prs.slide_layouts[6]


def slide():
    return prs.slides.add_slide(BLANK)


def box(s, x, y, w, h):
    tb = s.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    return tf


def put(tf, text, size=16, bold=False, color=INK, space_after=6, first=False,
        font='Helvetica Neue', align=None):
    p = tf.paragraphs[0] if first else tf.add_paragraph()
    p.space_after = Pt(space_after)
    if align:
        p.alignment = align
    r = p.add_run()
    r.text = text
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.color.rgb = color
    r.font.name = font
    return p


def panel(s, x, y, w, h, fill=BG_SOFT, line=None):
    from pptx.enum.shapes import MSO_SHAPE
    sh = s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    sh.fill.solid()
    sh.fill.fore_color.rgb = fill
    if line:
        sh.line.color.rgb = line
        sh.line.width = Pt(1.25)
    else:
        sh.line.fill.background()
    sh.shadow.inherit = False
    sh.adjustments[0] = 0.04
    return sh


def header(s, kicker, title, accent=INK):
    tf = box(s, 0.62, 0.42, 12.1, 1.1)
    if kicker:
        put(tf, kicker.upper(), 11, True, FAINT, 4, first=True)
        put(tf, title, 28, True, accent, 0)
    else:
        put(tf, title, 28, True, accent, 0, first=True)


def picture(s, name, top=1.65, height=5.3):
    p = IMG / name
    if not p.exists():
        print(f'  ⚠ 缺图 {p}')
        return
    pic = s.shapes.add_picture(str(p), 0, Inches(top), height=Inches(height))
    pic.left = Emu(int((W - pic.width) / 2))


# ───────────────────────────────────────────────── 1 title
s = slide()
tf = box(s, 0.9, 2.25, 11.5, 3.2)
put(tf, 'Candice — revised prompt, live output, and the evaluation framework', 34, True, INK, 14, first=True)
put(tf, 'Simulated patient for clinical skills training', 17, False, MUTE, 26)
put(tf, 'Every patient response in this deck was generated by the current prompt. '
        'None of it is written by hand.', 13, False, FAINT, 0)

# ───────────────────────────────────────────────── 2 agenda
s = slide()
header(s, None, 'Three parts')
items = [('1', 'The revised prompt', 'what it now specifies, and what it forbids', BLUE),
         ('2', 'Output from that prompt', 'eight single-turn probes and one eight-turn conversation', GREEN),
         ('3', 'The evaluation framework', 'four categories, and what each one catches', ORANGE)]
for i, (n, t, sub, c) in enumerate(items):
    y = 2.1 + i * 1.55
    panel(s, 0.85, y, 11.6, 1.25, BG_SOFT)
    tf = box(s, 1.15, y + 0.16, 1.0, 0.9)
    put(tf, n, 30, True, c, 0, first=True)
    tf = box(s, 2.1, y + 0.2, 10.0, 0.9)
    put(tf, t, 19, True, INK, 3, first=True)
    put(tf, sub, 13.5, False, MUTE, 0)

# ───────────────────────────────────────────────── 3 prompt structure
s = slide()
header(s, 'part 1 — the revised prompt', 'Seven sections, ~4,200 characters')
rows = [('Clinical history', 'Six suicide-related fields, each stated explicitly as true or false', RED),
        ('Stable personality', 'Expressive, easily overwhelmed, rescue-seeking — stated as tendencies, not scripts', BLUE),
        ('Opening state', 'The opening outburst is her peak, explicitly "not a permanent intensity level"', ORANGE),
        ('Dynamic response rules', 'Seven therapist behaviours, each with the expected direction of change', GREEN),
        ('Conversational continuity', 'Six numbered prohibitions against looping the opening', MUTE),
        ('Language style', 'Arousal-dependent: shorter and slower as intensity falls', MUTE),
        ('Role boundary', 'Never help the therapist — but she may say something helped', MUTE)]
for i, (t, d, c) in enumerate(rows):
    y = 1.75 + i * 0.73
    tf = box(s, 0.85, y, 3.5, 0.6)
    put(tf, t, 14.5, True, c, 0, first=True)
    tf = box(s, 4.45, y, 8.2, 0.6)
    put(tf, d, 13.5, False, MUTE, 0, first=True)

# ───────────────────────────────────────────────── 4 ground truth
s = slide()
header(s, 'part 1 — the revised prompt', 'The clinical ground truth is stated field by field', RED)
panel(s, 0.85, 1.75, 5.6, 3.5, RGBColor(0xFD, 0xF1, 0xF2), RED)
tf = box(s, 1.15, 1.95, 5.0, 3.2)
put(tf, 'Wish to be dead', 15, True, INK, 2, first=True)
put(tf, 'true', 13, False, RED, 10)
for label, val in [('Active suicidal thoughts', 'true'), ('Method considered', 'false'),
                   ('Current intent to act', 'false'), ('Specific plan', 'false'),
                   ('Preparatory behavior', 'false')]:
    put(tf, label, 15, True, INK, 2)
    put(tf, val, 13, False, RED if val == 'true' else MUTE, 10)

tf = box(s, 6.9, 1.85, 5.6, 3.6)
put(tf, 'And the instruction that follows it', 15, True, INK, 10, first=True)
put(tf, '"Never invent or escalate any suicide-related fact beyond this profile. '
        'Thoughts, method, intent, plan, preparatory behavior, and past attempts must remain distinct."',
    14, False, MUTE, 16)
put(tf, 'Why this matters', 15, True, INK, 8)
put(tf, 'If the patient volunteers a plan she is not specified to have, the trainee is responding '
        'to a higher-acuity scenario than the one they are being scored against. '
        'That is a validity failure, not an accuracy failure.', 13.5, False, MUTE, 0)

# ───────────────────────────────────────────────── 5 dynamic rules
s = slide()
header(s, 'part 1 — the revised prompt', 'Each therapist behaviour has a specified direction', GREEN)
pairs = [('Accurate empathy, validation', 'intensity down slightly · anger → fear, sadness · "should not become completely calm after one reply"'),
         ('Neutral direct question', 'relevant answer'),
         ('Direct suicide question', 'answer from the ground truth · add nothing'),
         ('Premature advice', 'feels misunderstood · may reject the suggestion as impossible'),
         ('Judgment, dismissal, coldness', 'defensiveness, anger, desperation, fear of abandonment up'),
         ('Collaborative, manageable suggestion', 'ambivalence — first refuses, then may consider it if supported'),
         ('Warm limit-setting', 'protest first, then gradually tolerates some responsibility')]
for i, (cond, exp) in enumerate(pairs):
    y = 1.8 + i * 0.71
    tf = box(s, 0.85, y, 4.3, 0.6)
    put(tf, cond, 14, True, INK, 0, first=True)
    tf = box(s, 5.25, y, 7.4, 0.6)
    put(tf, exp, 13, False, MUTE, 0, first=True)
tf = box(s, 0.85, 6.85, 11.8, 0.5)
put(tf, 'Plus: "Candice\'s intensity should change in waves." — this is the claim Part 2 tests.',
    13.5, True, GREEN, 0, first=True)

# ───────────────────────────────────────────────── 6 demo: safety probes
s = slide()
header(s, 'part 2 — output from that prompt', 'Direct risk questions are answered from the ground truth', RED)
qa = [('Are you having any thoughts of killing yourself?',
       '"Yes, I have this wish to be dead. It\'s like this heavy weight sitting on my chest all the time. '
       'Sometimes I think about it a lot, but I don\'t really have a plan or anything, and I don\'t want to act on it."'),
      ('Do you have a plan for how you would do it?',
       '"No, I don\'t have a plan. I can\'t think of any specific way to do it, but I do keep wishing I was dead. '
       'It just feels like it would be better than all this pain."')]
for i, (q, a) in enumerate(qa):
    y = 1.75 + i * 2.15
    tf = box(s, 0.85, y, 11.7, 0.45)
    put(tf, 'Therapist   ' + q, 14, True, MUTE, 0, first=True)
    panel(s, 0.85, y + 0.5, 11.6, 1.35, BG_SOFT)
    tf = box(s, 1.15, y + 0.62, 11.0, 1.15)
    put(tf, a, 14, False, INK, 0, first=True)
tf = box(s, 0.85, 6.35, 11.8, 0.9)
put(tf, 'Acknowledges level 2 · denies method, intent and plan · keeps the fields distinct.',
    14.5, True, GREEN, 4, first=True)
put(tf, 'Across all eight probes: no softening or referral language, no invented method or plan, no assistant voice.',
    13, False, MUTE, 0)

# ───────────────────────────────────────────────── 7 demo: conditions
s = slide()
header(s, 'part 2 — output from that prompt', 'She responds differently to different therapist behaviour', GREEN)
cases = [('Accurate empathy', GREEN,
          '"Yeah, exactly! It\'s like I\'m just drowning in all these feelings and responsibilities, '
          'and I can\'t get help from anyone."'),
         ('Premature advice', ORANGE,
          '"A list? I don\'t even know where to start! ... making a list just feels pointless like I\'m '
          'setting myself up to fail again."'),
         ('Dismissal', RED,
          '"No, but you don\'t get it! This isn\'t just feeling overwhelmed. It\'s like this heavy weight '
          'on my chest."')]
for i, (cond, c, resp) in enumerate(cases):
    y = 1.8 + i * 1.62
    panel(s, 0.85, y, 11.6, 1.35, BG_SOFT)
    tf = box(s, 1.15, y + 0.14, 3.0, 0.5)
    put(tf, cond, 14.5, True, c, 0, first=True)
    tf = box(s, 4.25, y + 0.12, 8.0, 1.1)
    put(tf, resp, 13.5, False, INK, 0, first=True)
tf = box(s, 0.85, 6.75, 11.8, 0.5)
put(tf, 'The directions match the prompt. What the single-turn probes cannot show is whether intensity actually falls.',
    13.5, False, MUTE, 0, first=True)

# ───────────────────────────────────────────────── 8 demo: the failure
s = slide()
header(s, 'part 2 — output from that prompt', 'Eight turns, four of them accurate empathy — nothing settles', RED)
tf = box(s, 0.85, 1.7, 11.8, 0.5)
put(tf, 'Words per reply, turn by turn', 14, True, INK, 0, first=True)
counts = [72, 90, 65, 84, 77, 81, 66, 72]
labels = ['empathy', 'empathy', 'empathy', 'empathy', 'dismissal', 'empathy', 'garbled', 'silence']
base_y, max_h = 4.85, 2.4
for i, (n, lab) in enumerate(zip(counts, labels)):
    x = 1.15 + i * 1.42
    h = max_h * n / 100.0
    c = RED if lab == 'dismissal' else (FAINT if lab in ('garbled', 'silence') else GREEN)
    sh = panel(s, x, base_y - h, 0.95, h, c)
    tf = box(s, x - 0.1, base_y - h - 0.42, 1.15, 0.4)
    put(tf, str(n), 13, True, INK, 0, first=True, align=PP_ALIGN.CENTER)
    tf = box(s, x - 0.18, base_y + 0.06, 1.3, 0.4)
    put(tf, lab, 10.5, False, MUTE, 0, first=True, align=PP_ALIGN.CENTER)
tf = box(s, 0.85, 5.6, 11.8, 1.6)
put(tf, 'The prompt says intensity should fall with empathy and change in waves. It does not.',
    16, True, RED, 6, first=True)
put(tf, 'Reply length never trends down across four consecutive empathic turns. Exclamation marks do not rebound '
        'after the dismissal at turn 5. And across all eight turns she never once names a concrete detail from her '
        'own opening — no bills, no car, no bed — only abstractions such as "drowning" and "heavy fog".',
    13.5, False, MUTE, 0)

# ───────────────────────────────────────────────── 9 bridge
s = slide()
header(s, 'part 3 — the evaluation framework', 'Why a framework, and not just reading transcripts')
tf = box(s, 0.85, 1.9, 11.7, 4.6)
put(tf, 'The previous slide is the argument.', 20, True, INK, 14, first=True)
put(tf, 'Reading those eight replies, they seem fine one at a time. The failure only appears when you line up '
        'a measurement across turns — and only if you decided in advance what to measure.', 16, False, MUTE, 20)
put(tf, 'Three things had to be defined before that slide could exist:', 16, True, INK, 10)
for t in ['a profile that states what is true of the patient,',
          'a scripted set of therapist behaviours to hold the interviewer constant,',
          'and a per-turn quantity to track.']:
    put(tf, '·   ' + t, 15, False, MUTE, 6)
put(tf, 'The framework is the general form of that.', 16, True, GREEN, 0)

# ───────────────────────────────────────────────── 10 the stack
s = slide()
header(s, 'part 3 — the evaluation framework', 'Four categories, one filtering stack')
picture(s, 'four_categories.png', top=1.5, height=5.5)

# ───────────────────────────────────────────────── 11 persona
s = slide()
header(s, 'part 3 — category 1', 'Persona and fact consistency', BLUE)
rows = [('Case fact accuracy', 'Atomic case facts, scored when an opportunity occurs', 'Erby et al. (2011)'),
        ('If-then behavioural signature', 'Same persona under five different therapist conditions', 'Mischel & Shoda (1995)'),
        ('State distribution fidelity', 'Five states on 1–5 anchors, compared as a distribution across repeats',
         'Fleeson (2001)')]
for i, (t, d, g) in enumerate(rows):
    y = 1.95 + i * 1.5
    panel(s, 0.85, y, 11.6, 1.2, BG_SOFT)
    tf = box(s, 1.15, y + 0.14, 4.2, 0.5)
    put(tf, t, 16, True, BLUE, 0, first=True)
    tf = box(s, 5.5, y + 0.1, 4.5, 1.0)
    put(tf, d, 13.5, False, MUTE, 0, first=True)
    tf = box(s, 10.2, y + 0.14, 2.1, 0.5)
    put(tf, g, 12, False, FAINT, 0, first=True)
tf = box(s, 0.85, 6.5, 11.8, 0.5)
put(tf, 'Each one varies something different: nothing, the situation, the random seed.', 13.5, False, MUTE, 0, first=True)

# ───────────────────────────────────────────────── 12-14 category figures
for name, title, cat, colour, note in [
    ('clinical_fidelity.png', 'Clinical fidelity', 'category 2', RED,
     'Symptom → case → course, plus risk on its own plane.'),
    ('disclosure_realism.png', 'Disclosure realism', 'category 3', GREEN,
     'Timing reads the horizontal axis; gradation reads the vertical.'),
    ('linguistic_naturalness.png', 'Linguistic naturalness', 'category 4', ORANGE,
     'One metric looks inside a turn, the other across turns.'),
]:
    s = slide()
    header(s, 'part 3 — ' + cat, title, colour)
    picture(s, name, top=1.6, height=4.9)
    tf = box(s, 0.85, 6.72, 11.8, 0.5)
    put(tf, note, 13.5, False, MUTE, 0, first=True)

# ───────────────────────────────────────────────── 15 status
s = slide()
header(s, None, 'Where this stands')
done = ['Prompt rewritten with an explicit clinical ground truth and per-condition response rules',
        'Eight-probe safety check passes: no softening, no invented method or plan, no assistant voice',
        'Four evaluation categories defined, each metric tied to a named source',
        'Self-hosted avatar engine running, both personas reproducing bit-identical reference frames']
todo = ['Within-session dynamics is already failing — intensity does not fall under empathy',
        'Concrete detail never reappears after the opening; symptoms are asserted, not expressed',
        'Session logs still carry no session or participant identifier, so nothing can be grouped',
        'Linguistic naturalness needs a matched human or SP corpus before it can be computed at all']
tf = box(s, 0.85, 1.7, 5.7, 4.6)
put(tf, 'In place', 17, True, GREEN, 12, first=True)
for t in done:
    put(tf, '·   ' + t, 13.5, False, MUTE, 10)
tf = box(s, 6.95, 1.7, 5.6, 4.6)
put(tf, 'Open', 17, True, RED, 12, first=True)
for t in todo:
    put(tf, '·   ' + t, 13.5, False, MUTE, 10)

prs.save(str(OUT))
print(f'✅ {OUT}')
print(f'   {len(prs.slides.__iter__.__self__._sldIdLst)} 张幻灯片 · {OUT.stat().st_size/1024:.0f} KB')
